In [1]:
import tensorflow as tf

In [2]:
X = tf.Variable([[0.,0.],[0.,1.],[1.,0.],[1.,1.]],dtype=tf.float32)
print(X)

<tf.Variable 'Variable:0' shape=(4, 2) dtype=float32, numpy=
array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]], dtype=float32)>


In [3]:
y = tf.Variable([0, 1, 1, 1], dtype=tf.float32)
y = tf.reshape(y, [4,1])
print(y)

tf.Tensor(
[[0.]
 [1.]
 [1.]
 [1.]], shape=(4, 1), dtype=float32)


In [4]:
NUM_FEATURES = X.shape[1]
OUTPUT_SIZE = 1

In [5]:
W = tf.Variable(tf.zeros([NUM_FEATURES, OUTPUT_SIZE]), dtype=tf.float32)
print(W)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>


In [6]:
B = tf.Variable(tf.zeros([OUTPUT_SIZE, 1]), dtype=tf.float32)
print(B)

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.]], dtype=float32)>


In [7]:
def perceptron(X):
  z = tf.add(tf.matmul(X, W), B)
  output = tf.sigmoid(z)
  return output
print(perceptron(X))

tf.Tensor(
[[0.5]
 [0.5]
 [0.5]
 [0.5]], shape=(4, 1), dtype=float32)


In [9]:
learning_rate = 0.01
optimizer = tf.optimizers.SGD(learning_rate)
no_of_epochs = 1000

In [10]:
for n in range(no_of_epochs):
    with tf.GradientTape() as tape:
        # Calculate loss
        logits = perceptron(X)
        loss = tf.reduce_mean(
            tf.nn.sigmoid_cross_entropy_with_logits(
                labels=y,
                logits=logits
            )
        )

    # Calculate gradients
    gradients = tape.gradient(loss, [W, B])

    # Apply gradients
    optimizer.apply_gradients(zip(gradients, [W, B]))

In [11]:
print(W)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[0.41244915],
       [0.41244915]], dtype=float32)>


In [12]:
print(B)

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.23606588]], dtype=float32)>
