In [1]:
import tensorflow as tf

In [2]:
A=tf.Variable([[1,2,3,4], \
[5,6,7,8], \
[9,10,11,12], \
[13,14,15,16], \
[17,18,19,20]])

In [3]:
tf.print(A)

[[1 2 3 4]
 [5 6 7 8]
 [9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [4]:
A.shape

TensorShape([5, 4])

In [5]:
tf.print(tf.reshape(A,[5,4,1]))

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]

 [[9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]

 [[17]
  [18]
  [19]
  [20]]]


In [6]:
A.shape

TensorShape([5, 4])

In [7]:
A = tf.reshape(A,[5,4,1])

In [8]:
A.shape

TensorShape([5, 4, 1])

In [9]:
tf.print(A)

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]

 [[9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]

 [[17]
  [18]
  [19]
  [20]]]
