In [1]:
import tensorflow as tf
X=tf.Variable([[1,2,3],[4,5,6]])
Y=tf.Variable([[7,8],[9,10],[11,12]])

In [2]:
tf.print(X)

[[1 2 3]
 [4 5 6]]


In [3]:
tf.print(Y)

[[7 8]
 [9 10]
 [11 12]]


In [4]:
c1=tf.matmul(X,Y)

In [5]:
tf.print(c1)

[[58 64]
 [139 154]]


In [7]:
c2=tf.matmul(Y,X)

In [8]:
tf.print(c2)

[[39 54 69]
 [49 68 87]
 [59 82 105]]
